title: Nouraldin Hassan
# description: >-
#   Page of an Algonquin College graduate.
baseurl: "" # GitHub username repo = root
url: "https://nouraldinhassan.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
